#!/bin/bash

# To check if user is running on sudo
if [[ ! $EUID == 0 ]]; then
    echo "$0 is not running as root. Please use sudo."
    exit 1
fi

# Create user webgen with home directory at /var/lib/webgen
useradd -r -m -d /var/lib/webgen -s /usr/bin/nologin webgen 
# -r makes sure the ID is below 1000
# -m creates the home dir 
# -d assigns the home dir
# -s sets the shell of the webgen 
# /usr/sbin/nologin is a shell that prevents other users from logging in as webgen 

# to check you created webgen run this command:
# cat /etc/passwd | grep webgen

# Create /bin /documents and /HTML directories
mkdir -p /var/lib/webgen/bin 
mkdir -p /var/lib/webgen/documents
mkdir -p /var/lib/webgen/HTML
# -p creates the entire path

# Ensure user and group webgen has ownership of the directories
chown -R webgen:webgen /var/lib/webgen
# -R recursive 

# Clone the repo containing the generate_index script
git clone https://git.sr.ht/~nathan_climbs/2420-as2-start 
# You must clone this repo to get the generate_index script

# Make the generate_index script executable
chmod +x /var/lib/webgen/bin/generate_index
# +x makes the script executable

# move generate_index script to /bin
mv ./generate_index /var/lib/webgen/bin/

# Create a service file that will run generate_index script
cat > /etc/systemd/system/generate-index.service <<- "alucard" 
[Unit]
Description=Generate index.html
After=network-online.target  
Wants=network-online.target 

[Service]
User=webgen
Group=webgen
ExecStart=/var/lib/webgen/bin/generate_index
Type=oneshot

[Install]
WantedBy=multi-user.target
alucard

# Create generate-index.timer file that will run the service everyday at 05:00
cat > /etc/systemd/system/generate-index.timer <<- "hellsing"
[Unit]
Description=Run generate-index.service everyday at 05:00

[Timer]
OnCalendar=*-*-* 05:00:00 America/Vancouver
Persistent=true

[Install]
WantedBy=timers.target
hellsing